### ISSUE TITLE
No title

### ISSUE THREAD

**Issue by NoverNobida** [albertodeago/my-notes-pwa#1]
Some notes have no title, such as sticky notes. Hope to display the content of the note without filling in the title.

**Comment by albertodeago** [comment]
Hi, I'm no longer using and maintaining this. It's been more of a toy project to experiment with PWA. 
If you need a note taking app (but millions of time better than this) I suggest you to have a look to https://github.com/notable/notable

If you instead want to use this project and just want that "feature" of notes without title point an example to me and I'll see if I can't implement easily

**Comment by NoverNobida** [comment]
@albertodeago Thanks!
